#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

export ARMBIAN_SYSTEM_CFG_FILE="$BOOT_PATH/system.cfg"

########################################
# Enable dsi asn KS  #
########################################

sed -i 's/^overlays=hdmi$/overlays=dsi/' "${ARMBIAN_CONFIG_TXT_FILE}"
sed -i 's/^#ks_src='HDMI-1'$/ks_src='DSI-1'/' "${ARMBIAN_SYSTEM_CFG_FILE}"
