#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/dw-0/kiauh"
DEPS="git"

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS}"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning Repository"
sudo -u "${BASE_USER}" git clone ${REPO} kiauh

########################################
# Install HelixScreen extension        #
########################################

sudo -u "${BASE_USER}" git clone --depth 1 https://github.com/prestonbrown/helixscreen.git helixscreen
cp -r ./helixscreen/scripts/kiauh/helixscreen ./kiauh/kiauh/extensions/
chown -R "${BASE_USER}:${BASE_USER}" ./kiauh/kiauh/extensions/helixscreen

rm -rf helixscreen

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1
