#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/Arksine/katapult"
DEPS="git python3-serial"

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS}"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning Repository"
sudo -u "${BASE_USER}" git clone ${REPO} katapult

########################################
# Add config to moonraker.conf         #
########################################

if [[ -f $MOONRAKER_CONFIG ]]; then
    cat /files/moonraker_katapult.conf >> "$MOONRAKER_CONFIG"
fi

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1