#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/worksasintended/klipper_linear_movement_analysis.git"
SRC_DIR="/home/${BASE_USER}/klipper_linear_movement_analysis"


echo_green "Installing Klipper Linear Movement Analysis by MarschallMarc#6420"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

#######################################
# Clone repository                     #
########################################

echo "Cloning Repository"
sudo -u "${BASE_USER}" git clone ${REPO} ${SRC_DIR}


EXTENSION_PATH="/home/${BASE_USER}/klipper_linear_movement_analysis"
SCRIPT_NAME="linear_movement_vibrations.py"

ratos extensions register klipper "linear_movement_analysis" "${EXTENSION_PATH}/${SCRIPT_NAME}"

echo_green "Installing matplotlib for python 2"

sudo -u "${BASE_USER}" /home/"${BASE_USER}"/klippy-env/bin/pip install -v matplotlib

popd &> /dev/null || exit 1
