#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

SRC_DIR="/home/${BASE_USER}/klipper"
ENV_DIR="/home/${BASE_USER}/klippy-env"

# Offizielles Upstream-Repository für Moonraker-Kompatibilität
OFFICIAL_REPO="https://github.com/Klipper3d/klipper.git"
OFFICIAL_BRANCH="master"

# RatOS-Spezifischer Fork für die Code-Basis
RATOS_FORK_REPO="https://github.com/Lino77/klipper.git"
RATOS_FORK_BRANCH="ratos/v3.0.x"

DEPS=(git \
      # Packages for python cffi
      virtualenv python3-dev libffi-dev build-essential \
      # kconfig requirements
      libncurses-dev pkg-config \
      # hub-ctrl
      libusb-dev libusb-1.0-0-dev \
      # AVR chip installation and building
      avrdude gcc-avr binutils-avr avr-libc \
      # ARM chip installation and building
      stm32flash dfu-util libnewlib-arm-none-eabi \
      gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0 \
      # Input shaper dependencies
      python3-numpy python3-matplotlib libopenblas-dev \
      )

# libatlas-base-dev was merged into libopenblas-dev in Trixie and is no longer available
if [ "$(is_in_apt libatlas-base-dev)" -eq 1 ]; then
  DEPS+=(libatlas-base-dev)
fi

########################################
# Install Dependencies                 #
########################################

echo "Installing Dependencies"
apt-get install --yes "${DEPS[@]}"

########################################
# Add user to groups                   #
########################################

## Make sure user pi has access to serial ports
usermod -a -G "tty,dialout" "${BASE_USER}"

########################################
# Switch into home dir                 #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning official repo as origin ..."
# Klonen des offiziellen Repositories sorgt für korrekte Moonraker-Erkennung
sudo -u "${BASE_USER}" git clone -b ${OFFICIAL_BRANCH} ${OFFICIAL_REPO} klipper
pushd "klipper" &> /dev/null || exit 1

echo "Adding RatOS fork as secondary remote ..."
# Fork hinzufügen und Code holen
sudo -u "${BASE_USER}" git remote add ratos-fork ${RATOS_FORK_REPO}
sudo -u "${BASE_USER}" git fetch ratos-fork

echo "Checking out Fork-Code onto local master branch ..."
# Erstellt lokalen master basierend auf dem Fork, behält aber die Brücke zu origin/master bei
sudo -u "${BASE_USER}" git checkout -B ${OFFICIAL_BRANCH} ratos-fork/${RATOS_FORK_BRANCH}
sudo -u "${BASE_USER}" git branch --set-upstream-to=origin/${OFFICIAL_BRANCH} ${OFFICIAL_BRANCH}

popd &> /dev/null || exit 1

########################################
# Create printer_data directories      #
########################################

create_user_directories

########################################
# Create Virtualenv and install        #
# dependencies                         #
########################################

echo "Creating Virtualenv (klippy-env) ..."
sudo -u "${BASE_USER}" virtualenv -p python3 "${ENV_DIR}"
echo "Installing Python Dependencies ..."
sudo -u "${BASE_USER}" "${ENV_DIR}"/bin/pip install -r "${SRC_DIR}"/scripts/klippy-requirements.txt
echo "Installing NumPy in Virtualenv"

# Normally klipper would use "numpy<1.26", but that version does not support
# Python 3.13 which is now in Debian Trixie.
sudo -u "${BASE_USER}" "${ENV_DIR}"/bin/pip install "numpy"

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1

########################################
# Copy and enable service              #
########################################

echo "Copy Service and enable it"
cp /files/klipper.service /etc/systemd/system/klipper.service
cp /files/klipper.env /home/"${BASE_USER}"/printer_data/systemd/klipper.env
chown -R "${BASE_USER}":"${BASE_USER}" /home/"${BASE_USER}"/printer_data/systemd/klipper.env
systemctl_if_exists enable klipper.service
