#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

pushd "/home/${BASE_USER}" &> /dev/null || exit 1
echo_green "Installing DFU-util build dependencies"
apt-get -y install libusb-1.0-0-dev autoconf pandoc git
echo_green "Cloning and building DFU-util"
 # Fallback to GitLab mirror if the official SourceForge is down... which it often is..
git clone git://git.code.sf.net/p/dfu-util/dfu-util || git clone https://gitlab.com/dfu-util/dfu-util.git
pushd "/home/${BASE_USER}/dfu-util" &> /dev/null || exit 1
./autogen.sh
./configure
make install
echo_green "Removing DFU-util build dependencies"
apt-get -y purge pandoc
popd    &> /dev/null || exit 1   
popd    &> /dev/null || exit 1
