#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

if [[ ! -d /tmp ]]; then
	mkdir /tmp
fi

chmod 777 /tmp

# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
# in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"
# Download and install Node.js:
nvm install 20
# Verify the Node.js version:
node -v # Should print "v20.20.1".
# Download and install pnpm:
corepack enable pnpm
# Verify pnpm version:
pnpm -v

################
#curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
#curl -fsSL https://deb.nodesource.com/setup_22.x |  bash - &&\
apt update && apt-get -y clean && apt-get install -y nodejs
#npm install -g pnpm
###############
if ! which pnpm &> /dev/null; then
	echo "pnpm not found after sourcing"
	exit 1
fi
