#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

if [[ ! -d /tmp ]]; then
	mkdir /tmp
fi

chmod 777 /tmp

#curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
#apt update && apt install nodejs -y 
curl -fsSL https://deb.nodesource.com/setup_22.x |  bash - &&\
apt update && apt-get -y clean && apt-get install -y nodejs
npm install -g pnpm
if ! which pnpm &> /dev/null; then
	echo "pnpm not found after sourcing"
	exit 1
fi
