#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config


sudo -u "${BASE_USER}" /home/"${BASE_USER}"/printer_data/config/RatOS/scripts/ratos-post-install.sh

# Stop the configurator, curl will fail so disable exit on error
set +e
echo "Stopping the configurator"
curl 'http://localhost:3000/configure/api/trpc/kill' &> /dev/null
# Re-enable exit on error
set -e

retries=0
while [ "$(pgrep -f -c "ratos-configurator")" -gt 0 ]; do
    if [ $retries -gt 10 ]; then
        echo "Configurator did not stop, killing it..."
        pkill -f "ratos-configurator"
        if [ $retries -gt 12 ]; then
            echo "Configurator cannot be killed.. :("
            break
        fi
    fi
    echo "Waiting for configurator to stop... ${retries}s passed"
    sleep 1
    retries=$((retries + 1))
done

echo "Configurator stopped.."

if [ "$(pgrep -f -c "KlipperScreen")" -gt 0 ]; then
    echo "Stopping KlipperScreen"
    retries=0
    while [ "$(pgrep -f -c "KlipperScreen")" -gt 0 ]; do
        if [ $retries -gt 10 ]; then
            echo "KlipperScreen did not stop, killing it..."
            pkill -f "KlipperScreen"
            if [ $retries -gt 12 ]; then
                echo "KlipperScreen cannot be killed.. :("
                break
            fi
        fi
        echo "Waiting for KlipperScreen to stop... ${retries}s passed"
        sleep 1
        retries=$((retries + 1))
    done
fi

echo "List out all running processes"
ps aux
