#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/julianschill/klipper-led_effect.git"
SRC_DIR="/home/${BASE_USER}/klipper-led_effect"
KS_BUILD_INSTALL_SH="/home/${BASE_USER}/klipper-led_effect/install-led_effect.sh"

########################################
# Switch to BASE_USER home directory   #
########################################

pushd /home/"${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

sudo -u "${BASE_USER}" git clone ${REPO} "${SRC_DIR}"

########################################
# Run klipper-led_effect install routine    #
########################################

sudo -u "${BASE_USER}" "${KS_BUILD_INSTALL_SH}"

########################################
# Return to last directory             #
########################################

popd &> /dev/null || exit 1
