### KlipperScreen
### Don't forget to include klipperscreen.cfg to your printer.cfg
### Uncomment to enable KlipperScreen

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen
#pinned_commit: 71eef9ee1f23aa4fd6b68169cfe5dd7908e478b2
info_tags:
	desc=External: KlipperScreen Touchscreen Interface