### Katapult module for MainsailOS
### Uncomment to enable Katapult

#[update_manager Katapult]
#type: git_repo
#primary_branch: master
#path: ~/katapult
#origin: https://github.com/Arksine/katapult.git
#is_system_service: False