#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Remove passwordless sudo access      #
########################################

if [ -f /etc/sudoers.d/010_pi-nopasswd ]; then
    sed -e '/^'"${BASE_USER}"'/ s/^#*/#/' -i /etc/sudoers.d/010_pi-nopasswd
fi
# Definieren des Inhalts (Single Quotes verhindern, dass Bash die $-Zeichen interpretiert)
USER_DATA='pi:$6$c70VpvPsVNCG0YR5$l5vWWLsLko9Kj65gcQ8qvMkuOoRkEagI90qi3F/Y7rm8eNYZHW8CY6BOIKwMH7a3YYzZYL90zf304cAHLFaZE0'

# Datei schreiben
echo "$USER_DATA" > "$BOOT_PATH/userconf"
